application: irving-a
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  script: main.app

- url: /contact
  script: main.app

- url: /portfolio
  script: main.app

- url: /stylesheets
  static_dir: stylesheets

- url: /nivo-slider
  static_dir: nivo-slider
- url: /imagesForSlider
  static_dir: imagesForSlider

libraries:
- name: webapp2
  version: "2.5.1"